# pod.yml
apiVersion: v1
kind: Pod
metadata:
  name: testapi
  labels:
    app: testapi
    component: netcore-app
spec:
  containers:
    - image: p7165817/testapi
      imagePullPolicy: Always
      name: webapi
      ports:
        - containerPort: 80
---
# service.yml
apiVersion: v1
kind: Service
metadata:
  labels:
    app: testapi
  name: testapi
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 80
  selector:
    app: testapi
    component: netcore-app
  type: LoadBalancer